name: passing-workflow
on: [issue_comment]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g hello-world-npm
      - run: hello-world-npm
